### ISSUE TITLE
Unable to sign tx via the web wallet on devnet

### ISSUE THREAD

**Issue by DjackSounds** [ElrondNetwork/dapp-template#59]
On devnet, when trying to send a transaction from a dapp-template, I got this error on the console of the https://devnet-wallet.elrond.com website  :
`Sender not allowed: erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu`

This results in the popup to sign a tx not being displayed.

Note that this address is not mine.

**Comment by andiwi** [comment]
Some more infos on how to reproduce the bug (and a workaround):

I build transactions like that:
```
const contractFunction = new ContractFunction("functionName");
  let transaction = new Interaction(
    contract,
    contractFunction,
    contractFunction,
    [],
    contract.getAddress()
  )
    .withGasLimit(20000000)
    .buildTransaction();
```

The example above produces the described behaviour on devnet and mainnet.

A workaround is to add the sender to the transaction:

```
...
transaction.sender = new Address(accountInfo.address);
```

Thanks to
 https://github.com/ElvenTools/elven-tools-dapp/commit/cee5058c1a140ad615265871578bd6afa8c3393c#diff-f6d55502c3f0dcc3ae789b421080c942cf798b09ced0765d5158d93dc983be9fL138

**Comment by StanislavSava** [comment]
You cannot send a transaction from another address than the one that signs the transaction. In this case, the seems to be the sender in the transaction, but the transaction is signed by another address. This doesn't seem like an issue with dapp-template, this is just a template for showcasing dapp-core. If you want to extend the ContractFunction or Interaction classes, you probably need to open a PR with this in the erdjs repo.

**Comment by juliancwirko** [comment]
to add to that, despite that, the problem isn't related to dapp-template

As for me, I log in and sign the transaction with the same pem file, it doesn't work if I don't add the sender key in the payload, worked well sometime before, but now it only works when the transaction has the sender value. It still works well without it for other providers.

So, the tx must be signed by the same address because this is the only change that fixes it (adding the sender key to the payload).

btw, the demo https://dapp-template.elrond.com/ has the same problem
